create table Student2(Rollno int primary key,Name varchar(20),Address varchar(100),MobileNumber int)
insert into Student2 values(1, 'Mrunal', 'Chandra Nagar old Pardi Naka Bhanadra road', 98256)
insert into Student2 values(2, 'Purvi', 'Manewada road', 98456)
insert into Student2 values(3, 'Rohini', 'Burdi Fortune Mall', 96779)
insert into Student2 values(4, 'Aditi', 'Kharbi road', 85421)
insert into Student2 values(5, 'Sayali', 'Nanadanvan road', 78954)
insert into Student2 values(6, 'Trishala', 'Tilak Chowk Itawari', 9548)
insert into Student2 values(7, 'Vrushali', 'Tukdoji Putla', 9725)
insert into Student2 values(8, 'Sakhi', 'Amedkar square',  9088)
insert into Student2 values(9, 'Jayant', 'Darshan Colony', 7890)
insert into Student2 values(10, 'Chetan', 'Chatrapati Chowk',  994567)
select * from Student2